image_path: images/cornfield.bmp
save_path: images/cornfield
method: GKAN
steps: 10000
learning_rate: 1e-3
batch_size: 100000
image_save_steps: 50
mid: 500 # or number like 260
meta_learn: False
meta_path: None