_target_: src.learn.Learner
image_path: dataset/STI/Classic/airplane.bmp
model:
  _target_: src.models.INR
  method: GKAN
  mid: ${args.mid}
model_name: test
steps: 1000
learning_rate: 1e-3
batch_size: 100000
image_save_steps: 50
meta_learn: True
meta_path: ${meta_learn.save_path}/${meta_learn.model_name}